AquaticAlchemy/force-app/main/default/objects/Camp_Day__c/Camp_Day__c.object-meta.xml
<CustomObject>
    <label>Camp Day</label>
    <nameField>
        <label>Camp Day Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Camp Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AquaticAlchemy/force-app/main/default/objects/Camp_Day__c/fields/Activities__c.field-meta.xml
<CustomField>
    <fullName>Activities__c</fullName>
    <label>Activities</label>
    <length>88</length>
    <type>Text</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Camp_Day__c/fields/End_Time_String__c.field-meta.xml
<CustomField>
    <fullName>End_Time_String__c</fullName>
    <label>End Time String</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Camp_Day__c/fields/Public_Event__c.field-meta.xml
<CustomField>
    <fullName>Public_Event__c</fullName>
    <label>Public Event</label>
    <referenceTo>Public_Event__c</referenceTo>
    <relationshipLabel>Camp Days</relationshipLabel>
    <relationshipName>Camp_Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Camp_Day__c/fields/Start_Time_String__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_String__c</fullName>
    <label>Start Time String</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/Age_Group__c.field-meta.xml
<CustomField>
    <fullName>Age_Group__c</fullName>
    <label>Age Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5-10</fullName>
            </value>
            <value>
                <fullName>10-13</fullName>
            </value>
            <value>
                <fullName>14-17</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/Camp_Size__c.field-meta.xml
<CustomField>
    <fullName>Camp_Size__c</fullName>
    <label>Camp Size</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/EndDateString__c.field-meta.xml
<CustomField>
    <fullName>EndDateString__c</fullName>
    <label>EndDateString</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/StartDateString__c.field-meta.xml
<CustomField>
    <fullName>StartDateString__c</fullName>
    <label>StartDateString</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/Summer_Camp__c.field-meta.xml
<CustomField>
    <fullName>Summer_Camp__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Summer Camp?</label>
    <type>Checkbox</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/Swim_Level__c.field-meta.xml
<CustomField>
    <fullName>Swim_Level__c</fullName>
    <label>Swim Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AquaticAlchemy/force-app/main/default/classes/AccordionAuraController.cls
///////////////////////////////////////////////////////////////
//
// Name: AccordionAuraController.cls
// Author: David Serrano, Salesforce Developer
// Created: 05/13/21
// Updated: 05/14/21
// Description: Apex Aura controller to return lists of necessary data, such as Knowledge Articles, Public Events, and Camp Day Schedules.
//
/////////////////////////////////////////////////////////////// 

public class AccordionAuraController {
    
    @AuraEnabled
    public static List<Knowledge__kav> getArticles(){
        List<Knowledge__kav> articles = [SELECT Question__c, Answer__c FROM Knowledge__kav WHERE RecordTypeId='0125e000000YMw1AAG' LIMIT 10 ];

        return articles;
    }
    
    @AuraEnabled
    public static List<Public_event__c> getCampSchedules(){
        List<Public_event__c> campEvent = [SELECT Id,
                                           Name,
                                           Camp_Size__c,
                                           Age_Group__c,
                                           Swim_Level__c,
                                           StartDateTime__c,
                                           EndDateTime__c,
                                           Description__c,
                                           StartDateString__c,
                                           EndDateString__c
                                           FROM Public_event__c WHERE Summer_Camp__c=true LIMIT 3 ];
        

        for(Public_event__c e:campEvent){
            if(e.StartDateTime__c != NULL  && e.EndDateTime__c != NULL){
                e.StartDateString__c = e.StartDateTime__c.format('MMM dd, yyyy');
                e.EndDateString__c = e.EndDateTime__c.format('MMM dd, yyyy');
            }
        }
    
        
        return campEvent;
    }
    
    @AuraEnabled
    public static List<Camp_Day__c> getDaySchedules(Id campId){
        List<Camp_Day__c> daySchedules = [SELECT Name,
                                          Start_Time__c,
                                          End_Time__c, 
                                          Start_Time_String__c,
                                          End_Time_String__c,
                                          Activities__c
                                          FROM Camp_Day__c WHERE Public_Event__c=:campId ORDER BY Start_Time__c ASC LIMIT 5] ;
        
        for(Camp_Day__c d:daySchedules){
            if(d.Start_Time__c != NULL  && d.End_Time__c != NULL){
                d.Start_Time_String__c = d.Start_Time__c.format('hh:mm a');
                d.End_Time_String__c = d.End_Time__c.format('hh:mm a');
            }
        }

        return daySchedules;
    }
    
    
}