AquaticAlchemy/force-app/main/default/objects/Public_Event__c/Public_Event__c.object-meta.xml
<CustomObject>
    <label>Public Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Public Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/ActivityDate__c.field-meta.xml
<CustomField>
    <fullName>ActivityDate__c</fullName>
    <label>Activity Date</label>
    <type>DateTime</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

AquaticAlchemy/force-app/main/default/objects/Public_Event__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aquatic Class</fullName>
            </value>
            <value>
                <fullName>Swim Meet</fullName>
            </value>
            <value>
                <fullName>Birthday Party</fullName>
            </value>
            <value>
                <fullName>Private Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AquaticAlchemy/force-app/main/default/classes/ApexFilterControllerTest.cls
@isTest
public class ApexFilterControllerTest {
	
    @isTest
    public static void TestFilter(){
        Datetime activityDate = System.today();
        Datetime endTime = activityDate+1;
        Public_Event__c event = new Public_Event__c(Subject__c = 'Aquatic Class', ActivityDate__c = activityDate, EndDateTime__c = endTime, IsAllDayEvent__c = false);
        insert event;
        ApexFilterController.FilterEvents(System.today());
    }
        
    
}